Traceback (most recent call last):
  File "NanoIgset.py", line 21, in <module>
    run=pypath(sys.argv[2])
IndexError: list index out of range
